[assembly: InternalsVisibleTo("KeyValium.Benchmarks")]
[assembly: InternalsVisibleTo("KeyValium.Inspector")]
[assembly: InternalsVisibleTo("KeyValium.Performance")]
//[assembly: InternalsVisibleTo("KeyValium.Playground")]
[assembly: InternalsVisibleTo("KeyValium.TestBench")]
[assembly: InternalsVisibleTo("KeyValium.Tests")]
[assembly: InternalsVisibleTo("KeyValium.UnendingTest")]